name: Deploy NuGet

on:
  workflow_call:
    inputs:      
      runs-on:
        type: string
        default: ubuntu-latest
    secrets:
      nuget-api-key:
        required: true

jobs:
  packing:  
    name: Publish NuGet Packages
    runs-on: ${{ inputs.runs-on }}
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: ./packages
        
      - name: Publish NuGet packages
        run: |
          echo "Publishing NuGet packages..."
          for file in ./packages/*.nupkg; do
            echo "Publishing $file"
            dotnet nuget push "$file" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nuget-api-key }}
          done
        env:
          NUGET_API_KEY: ${{ secrets.nuget-api-key }}
        working-directory: ${{ github.workspace }}

      - name: List published packages
        run: |
          echo "Listing published packages:"
          dotnet nuget list source
        working-directory: ${{ github.workspace }}

      - name: Cleanup
        run: |
          echo "Cleaning up..."
          rm -rf ./packages
        working-directory: ${{ github.workspace }}